name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ubuntu packages
        run: sudo apt-get install bash make jq

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Rust target
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-wasm32-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-wasm32-

      - uses: cargo-bins/cargo-binstall@main
        name: Install cargo-binstall
        with:
          version: latest

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install rust wasm32-wasip2
        run: rustup target add wasm32-wasip2

      - name: Install wasi components
        run: |
          cargo binstall cargo-component warg-cli wkg --locked --no-confirm
          wkg config --default-registry wa.dev

      - name: Install deps
        run: make setup

      - name: Build
        run: make build
